apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: wp-sitio
  labels:
    run: wp-sitio
spec:
  selector:
    matchLabels:
      run: wp-sitio
  serviceName: 'wp-sitio'
  template:
    metadata:
      generateName: wp-sitio
      labels:
        run: wp-sitio
    spec:
      containers:
        - name: wp-sitio
          image: wordpress:php7.4-apache
          imagePullPolicy: IfNotPresent
          env:
            - name: WORDPRESS_DB_HOST
              valueFrom:
                secretKeyRef:
                  name: wp-sitio-sec
                  key: WORDPRESS_DB_HOST
            - name: WORDPRESS_DB_USER
              valueFrom:
                secretKeyRef:
                  name: wp-sitio-sec
                  key: WORDPRESS_DB_USER
            - name: WORDPRESS_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: wp-sitio-sec
                  key: WORDPRESS_DB_PASSWORD
            - name: WORDPRESS_DB_NAME
              valueFrom:
                secretKeyRef:
                  name: wp-sitio-sec
                  key: WORDPRESS_DB_NAME

          ports:
            - name: wp-sitio
              containerPort: 80
          volumeMounts:
            - mountPath: '/var/www/html'
              name: wp-sitio-data

          lifecycle:
            postStart:
              exec:
                command: ['/bin/sh', '-c', 'chmod 555 /var/www/html']
      volumes:
        - name: wp-sitio-sec
          secret:
            secretName: wp-sitio-sec

  volumeClaimTemplates:
    - metadata:
        name: wp-sitio-data
      spec:
        accessModes: ['ReadWriteOnce']
        resources:
          requests:
            storage: 10Gi
