apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    kubernetes.io/ingress.class: nginx
    kubernetes.io/tls-acme: 'false'
  name: wp-sitio-ing
spec:
  rules:
    - host: coria-santiago-caso-3.my.kube.um.edu.ar
      http:
        paths:
          - backend:
              service:
                name: wp-sitio
                port:
                  number: 80
            path: /
            pathType: Prefix
