apiVersion: apps/v1
kind: StatefulSet

metadata:
  name: db-sts    #! Nombre del StatefulSet.
  labels:
    run: db-sts

spec:
  selector:
    matchLabels:
      run: db-sts
  serviceName: "db-sts"
  
  template:
    metadata:
      generateName: db-sts   #! Nombre base para los Pods.
      labels:
        run: db-sts

    spec:
      initContainers:  #! Contenedores que se ejecutan antes del contenedor principal.
      - name: "remove-lost-found"
        image: "busybox:1.25.0"
        imagePullPolicy: "IfNotPresent"
        command:  ["rm", "-fr", "/var/lib/mysql/lost+found"]
        volumeMounts:
        - name: mysql-data
          mountPath: /var/lib/mysql
          
      containers:  #! Contenedor principal.
        - name: wp-sitio-db
          image: mysql:5.7
          imagePullPolicy: IfNotPresent
          
          env:  #! Variables de entorno.
            - name: MYSQL_DATABASE  #! Nombre de la DB.
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: db-name

            - name: MYSQL_ROOT_PASSWORD  #! Contraseña DB.
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: db-pass

            - name: MYSQL_ROOT_USERNAME  #! Usuario DB.
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: db-user

          ports:  #! Puertos que el contenedor escuchará.
            - name: db-sts
              containerPort: 3306
          
          volumeMounts:
            - mountPath: "/var/lib/mysql"
              name: mysql-data

            - mountPath: "/docker-entrypoint-initdb.d"
              name: mysql-data
              readOnly: false

      volumes: 
        - name: db-secret
          secret:
            secretName: db-secret

        - name: mysql-data
          persistentVolumeClaim:
            claimName: mysql-data

        - name: mysql-volume
          persistentVolumeClaim:
            claimName: mysql-volume
        

  volumeClaimTemplates:  #! Volúmenes persistentes.
    - metadata:
        name: mysql-data
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 1Gi

    - metadata:
        name: mysql-volume
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 1Gi
