apiVersion: apps/v1
kind: StatefulSet

metadata:
  name: db-sts
  labels:
    run: db-sts

spec:
  selector:
    matchLabels:
      run: db-sts
  serviceName: 'db-sts'

  template:
    metadata:
      generateName: db-sts
      labels:
        run: db-sts

    spec:
      initContainers:
        - name: 'remove-lost-found'
          image: 'busybox:1.25.0'
          imagePullPolicy: 'IfNotPresent'
          command: ['rm', '-fr', '/var/lib/mysql/lost+found']
          volumeMounts:
            - name: mysql-data
              mountPath: /var/lib/mysql

      containers:
        - name: wp-sitio-db
          image: mysql:latest
          imagePullPolicy: IfNotPresent

          env:
            - name: MYSQL_DATABASE
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: db-name

            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: db-pass

            - name: MYSQL_ROOT_USERNAME
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: db-user

          ports:
            - name: db-sts
              containerPort: 3306

          volumeMounts:
            - mountPath: '/var/lib/mysql'
              name: mysql-data

            - mountPath: '/docker-entrypoint-initdb.d'
              name: mysql-data
              readOnly: false

      volumes:
        - name: db-secret
          secret:
            secretName: db-secret

        - name: mysql-data
          persistentVolumeClaim:
            claimName: mysql-data

        - name: mysql-volume
          persistentVolumeClaim:
            claimName: mysql-volume

  volumeClaimTemplates:
    - metadata:
        name: mysql-data
      spec:
        accessModes: ['ReadWriteOnce']
        resources:
          requests:
            storage: 10Gi

    - metadata:
        name: mysql-volume
      spec:
        accessModes: ['ReadWriteOnce']
        resources:
          requests:
            storage: 10Gi
