apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mb-sitio-db
  labels:
    run: mb-sitio-db
spec:
  selector:
    matchLabels:
      run: mb-sitio-db
  serviceName: 'mb-sitio-db'
  template:
    metadata:
      generateName: mb-sitio-db
      labels:
        run: mb-sitio-db
    spec:
      initContainers:
        - name: 'remove-lost-found'
          image: 'busybox:1.25.0'
          imagePullPolicy: 'IfNotPresent'
          command: ['rm', '-fr', '/var/lib/mysql/lost+found']
          volumeMounts:
            - name: mysql-data
              mountPath: /var/lib/mysql
      containers:
        - name: mb-sitio-db
          image: mysql:8.4
          imagePullPolicy: IfNotPresent
          env:
            - name: MYSQL_DATABASE
              valueFrom:
                secretKeyRef:
                  name: mb-sitio-db-sec
                  key: MYSQL_DATABASE
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mb-sitio-db-sec
                  key: MYSQL_ROOT_PASSWORD
          ports:
            - name: mb-sitio-db
              containerPort: 3306
          volumeMounts:
            - mountPath: '/var/lib/mysql'
              name: mysql-data
      volumes:
        - name: mb-sitio-db-sec
          secret:
            secretName: mb-sitio-db-sec

  volumeClaimTemplates:
    - metadata:
        name: mysql-data
      spec:
        accessModes: ['ReadWriteOnce']
        resources:
          requests:
            storage: 10Gi
